"""empty message

Revision ID: 39b814ba3529
Revises: 7c089d5d91b2
Create Date: 2025-12-23 17:58:53.470052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39b814ba3529'
down_revision = '7c089d5d91b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('comment_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_type', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
