"""empty message

Revision ID: 658eb3a97ab7
Revises: 7ea064c99dce
Create Date: 2025-12-25 15:29:38.822970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658eb3a97ab7'
down_revision = '7ea064c99dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_uid', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('reply_uid')

    # ### end Alembic commands ###
