"""empty message

Revision ID: 684ebaa5a87a
Revises: 6b02968d2766
Create Date: 2025-12-15 11:57:52.581984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684ebaa5a87a'
down_revision = '6b02968d2766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('title')
        batch_op.drop_column('photo')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=1000), nullable=True))
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=256), nullable=True))

    op.drop_table('post_contents')
    # ### end Alembic commands ###
