"""empty message

Revision ID: 7c089d5d91b2
Revises: 855c699b0224
Create Date: 2025-12-21 14:17:36.644141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c089d5d91b2'
down_revision = '855c699b0224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('like_count')
        batch_op.drop_column('comment_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('like_count', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
