"""empty message

Revision ID: 7deddaadc59f
Revises: 658eb3a97ab7
Create Date: 2025-12-27 20:00:08.639541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7deddaadc59f'
down_revision = '658eb3a97ab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE user_relationships ALTER COLUMN id TYPE INTEGER USING id::integer AUTO_INCREMENT")
    # with op.batch_alter_table('user_relationships', schema=None) as batch_op:
    #     batch_op.alter_column('id',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE user_relationships ALTER COLUMN id TYPE INTEGER USING id::integer AUTO_INCREMENT")

    # with op.batch_alter_table('user_relationships', schema=None) as batch_op:
    #     batch_op.alter_column('id',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            autoincrement=True)

    # ### end Alembic commands ###
