"""empty message

Revision ID: 7ea064c99dce
Revises: 39b814ba3529
Create Date: 2025-12-24 23:31:06.122322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea064c99dce'
down_revision = '39b814ba3529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('reply_user_uid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_user_uid', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
