"""empty message

Revision ID: 855c699b0224
Revises: d3db46edc230
Create Date: 2025-12-16 13:05:19.142363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855c699b0224'
down_revision = 'd3db46edc230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_image_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.String(), nullable=True),
    sa.Column('content_id', sa.String(), nullable=True),
    sa.Column('image_content_id', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_image_contents')
    # ### end Alembic commands ###
