"""empty message

Revision ID: d3db46edc230
Revises: 684ebaa5a87a
Create Date: 2025-12-15 14:05:11.260841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3db46edc230'
down_revision = '684ebaa5a87a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('index', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('text_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_contents', schema=None) as batch_op:
        batch_op.drop_column('text_type')
        batch_op.drop_column('type')
        batch_op.drop_column('index')
        batch_op.drop_column('content_id')

    # ### end Alembic commands ###
